version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: order-tracker-db
    environment:
      POSTGRES_USER: ot_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_tracker
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ot_user"]
      interval: 10s
      timeout: 5s
      retries: 5

